### ISSUE TITLE
Проблема с спрайтами унатхов

### ISSUE THREAD

**Issue by SabatonShip** [Corvax-Frontier/Frontier#30]
## Description

Всё на скриншотах - лапы сквозь одежду лезут. Мне больно
## Reproduction

Зайти в игру за унатха, померить разные вещи.
## Screenshots

![изображение](https://github.com/user-attachments/assets/94ca581a-431c-4508-9822-e6305be56351)
![изображение](https://github.com/user-attachments/assets/82fb875c-1eaf-438f-9bce-c813c1cb08ab)
![изображение](https://github.com/user-attachments/assets/595f39c0-d0e3-4c15-bf8c-ccf525d8f0e4)
![изображение](https://github.com/user-attachments/assets/ad8b0a12-fa4e-4b73-8028-163fd77a333d)
![изображение](https://github.com/user-attachments/assets/69f15606-e6e6-4d7a-85bd-6ebbb4941bc4)
![изображение](https://github.com/user-attachments/assets/7d7059ca-a322-4596-b138-d366fd393c51)

**Comment by Zekins3366** [comment]
Унатхи...
Посмотрим...

**Comment by Zekins3366** [comment]
Как я проверить, спрайты работают теперь нормально после моего внесения изменений #27 
Конечно не все спрайты идеальные, но явно стало во много раз лучше. Так что Задачу закрою, если есть что ещё сказать можете написать тут, я прочитаю, поправлю в будущем

**Comment by SabatonShip** [comment]
Как раз таки https://github.com/Corvax-Frontier/Frontier/pull/27 сломал ноги, потому что в игре используется спайт унатхов от оффов, а спрайты скафандров и обувь от корвакса. Сам попытаюсь тогда решить проблему
![изображение](https://github.com/user-attachments/assets/4f37f9ca-f4b2-4768-97f9-f885313c143b)
![изображение](https://github.com/user-attachments/assets/c25ccf56-7de7-4641-b026-bf6529c206d9)
![изображение](https://github.com/user-attachments/assets/f7e68659-3dda-49a4-a76a-39acb412dda7)
![изображение](https://github.com/user-attachments/assets/2af72460-cae7-4970-bc05-33e0c96d067e)

**Comment by Zekins3366** [comment]
> Как раз таки #27 сломал ноги, потому что в игре используется спайт унатхов от оффов, а спрайты скафандров и обувь от корвакса. Сам попытаюсь тогда решить проблему

А это у нас было обсуждение в закрытом чате, по поводу ног унатхов и их прямоты или наоборот. В итоге они все равно вышли кривые по офф коду xd
Пока с этим лучше ничего не делать, надо подождать апстрима, который в данный момент чинится официалами
